# Numpy 실습 (7/17)

### 1. NumPy 배열 생성 및 기본 연산

1-1. 배열 `a = [1, 2, 3]`과 `b = [4, 5, 6`을 생성하고 이 배열을 더하세요.

1-2. 배열 `a`와 `b`를 곱하세요.

### 2. 배열 생성 함수 사용

2-1. 2x3 형태의 0으로 초기화된 배열을 생성하세요.

2-2. 2x3 형태의 1로 초기화된 배열을 생성하세요.

2-3. 2x3 형태의 랜덤 값으로 채워진 배열을 생성하세요.


### 3. 배열 인덱싱 및 슬라이싱
3-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 인덱스 1의 요소를 출력하세요.

3-2. 배열 `arr`에서 인덱스 1부터 3까지의 요소를 출력하세요.

### 4. 배열 모양 변경
4-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`의 모양을 3x2로 변경하세요.

### 5. 배열 결합
5-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6]]`을 수직으로 결합하세요.

5-2. 배열 `a`와 `b`를 수평으로 결합하세요.

### 6. 배열 분할
6-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`을 수평으로 3등분하세요.

6-2. 배열 `arr`을 수직으로 2등분하세요.


### 7. 배열의 수학적 연산
7-1. 배열 `arr = [1, 2, 3, 4, 5]`의 합계를 구하세요.

7-2. 배열 `arr`의 평균을 구하세요.

7-3. 배열 `arr`의 표준 편차를 구하세요.

### 8. 논리 연산
8-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 20보다 큰 요소를 출력하세요.


### 9. 난수 생성 및 시드 설정
9-1. 3x3 형태의 난수 배열을 생성하세요.

9-2. 시드를 42로 설정한 후, 3x3 형태의 난수 배열을 생성하세요.

### 10. 배열 복사
10-1. 배열 `arr = [1, 2, 3, 4, 5]`의 뷰를 생성하고 첫 번째 요소를 10으로 변경하세요. 원본 배열을 확인하세요.

10-2. 배열 `arr`의 깊은 복사를 생성하고 첫 번째 요소를 20으로 변경하세요. 원본 배열을 확인하세요.

### 11. 배열 정렬
11-1. 배열 `arr = [5, 2, 9, 1, 5, 6]`을 정렬하세요.

11-2.정렬된 배열의 인덱스를 반환하세요.


### 12. 배열의 유니크 값 찾기
12-1. 배열 `arr = [1, 2, 2, 3, 4, 4, 4, 5]`에서 유니크 값을 찾으세요.

### 13. 행렬 곱셈
13-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6], [7, 8]]`의 행렬 곱을 계산하세요.


### 14. 조건부 선택
14-1. 배열 `arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`에서 짝수를 선택하세요.



### 15. 브로드캐스팅
15-1. 배열 `a = [[1, 2, 3], [4, 5, 6]]`과 배열 `b = [1, 0, 1]`을 더하세요.

In [1]:
# 패키지 불러오기
import numpy as np

### 1. NumPy 배열 생성 및 기본 연산

1-1. 배열 `a = [1, 2, 3]`과 `b = [4, 5, 6`을 생성하고 이 배열을 더하세요.

1-2. 배열 `a`와 `b`를 곱하세요.

In [23]:
# 배열 생성
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [3]:
# 배열 덧셈
c = a + b
print("Array addition:", c)

Array addition: [5 7 9]


In [4]:
# 배열 곱셈
d = a * b
print("Array multiplication:", d)

Array multiplication: [ 4 10 18]


### 2. 배열 생성 함수 사용

2-1. 2x3 형태의 0으로 초기화된 배열을 생성하세요.

2-2. 2x3 형태의 1로 초기화된 배열을 생성하세요.

2-3. 2x3 형태의 랜덤 값으로 채워진 배열을 생성하세요.

In [5]:
# 0으로 초기화된 배열 생성
zeros = np.zeros((2, 3))
print("Zeros array:\n", zeros)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 1로 초기화된 배열 생성
ones = np.ones((2, 3))
print("Ones array:\n", ones)

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# 랜덤 값으로 채워진 배열 생성
randoms = np.random.rand(2, 3)
print("Random array:\n", randoms)

Random array:
 [[0.21566901 0.93755405 0.76658239]
 [0.72171416 0.33718924 0.97697133]]


### 3. 배열 인덱싱 및 슬라이싱
3-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 인덱스 1의 요소를 출력하세요.

3-2. 배열 `arr`에서 인덱스 1부터 3까지의 요소를 출력하세요.

In [24]:
# arr 배열 생성
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [10]:
# 인덱싱
print("Element at index 1:", arr[1])

Element at index 1: 20


In [11]:
# 슬라이싱
print("Elements from index 1 to 3:", arr[1:4])

Elements from index 1 to 3: [20 30 40]



### 4. 배열 모양 변경
4-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`의 모양을 3x2로 변경하세요.

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# 배열 모양 변경
reshaped = arr.reshape((3, 2))
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


### 5. 배열 결합
5-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6]]`을 수직으로 결합하세요.

5-2. 배열 `a`와 `b`를 수평으로 결합하세요.

In [18]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a)
print(b)

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [14]:
# 배열 수직 결합
vertical = np.vstack((a, b))
print("Vertical stack:\n", vertical)

Vertical stack:
 [[1 2]
 [3 4]
 [5 6]]


In [15]:
# 배열 수평 결합
horizontal = np.hstack((a, b.T))
print("Horizontal stack:\n", horizontal)

Horizontal stack:
 [[1 2 5]
 [3 4 6]]


### 6. 배열 분할
6-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`을 수평으로 3등분하세요.

6-2. 배열 `arr`을 수직으로 2등분하세요.

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
# 수평 분할
split = np.hsplit(arr, 3)
print("Horizontal split:", split)

Horizontal split: [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [28]:
# 수직 분할
split = np.vsplit(arr, 2)
print("Vertical split:", split)

Vertical split: [array([[1, 2, 3]]), array([[4, 5, 6]])]


### 7. 배열의 수학적 연산
7-1. 배열 `arr = [1, 2, 3, 4, 5]`의 합계를 구하세요.

7-2. 배열 `arr`의 평균을 구하세요.

7-3. 배열 `arr`의 표준 편차를 구하세요.

In [29]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [30]:
# 배열 합계
print("Sum:", np.sum(arr))

Sum: 15


In [32]:
# 배열 평균
print("Mean:", np.mean(arr))

Mean: 3.0


In [33]:
# 배열 표준 편차
print("Standard Deviation:", np.std(arr))

Standard Deviation: 1.4142135623730951


### 8. 논리 연산
8-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 20보다 큰 요소를 출력하세요.

In [34]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [35]:
# 논리 조건
print("Elements greater than 20:", arr[arr > 20])

Elements greater than 20: [30 40 50]


### 9. 난수 생성 및 시드 설정
9-1. 3x3 형태의 난수 배열을 생성하세요.

9-2. 시드를 42로 설정한 후, 3x3 형태의 난수 배열을 생성하세요.

In [36]:
# 난수 생성
randoms = np.random.rand(3, 3)
print("Random array:\n", randoms)

Random array:
 [[0.73321437 0.24657375 0.84754921]
 [0.11436358 0.16429013 0.86410958]
 [0.0232986  0.40280466 0.13367729]]


In [37]:
# 시드 설정
np.random.seed(42)
randoms_seeded = np.random.rand(3, 3)
print("Seeded random array:\n", randoms_seeded)

Seeded random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


### 10. 배열 복사
10-1. 배열 `arr = [1, 2, 3, 4, 5]`의 뷰를 생성하고 첫 번째 요소를 10으로 변경하세요. 원본 배열을 확인하세요.

10-2. 배열 `arr`의 깊은 복사를 생성하고 첫 번째 요소를 20으로 변경하세요. 원본 배열을 확인하세요.


In [38]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [39]:
# 얕은 복사 (뷰)
view = arr.view()
view[0] = 10
print("Original array after view modification:", arr)

Original array after view modification: [10  2  3  4  5]


In [40]:
# 깊은 복사
copy = arr.copy()
copy[0] = 20
print("Original array after copy modification:", arr)

Original array after copy modification: [10  2  3  4  5]


### 11. 배열 정렬
11-1. 배열 `arr = [5, 2, 9, 1, 5, 6]`을 정렬하세요.

11-2.정렬된 배열의 인덱스를 반환하세요.


In [41]:
arr = np.array([5, 2, 9, 1, 5, 6])
print(arr)

[5 2 9 1 5 6]


In [42]:
# 정렬된 배열
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

Sorted array: [1 2 5 5 6 9]


In [43]:
# 인덱스 기반 정렬
sorted_indices = np.argsort(arr)
print("Indices of sorted elements:", sorted_indices)

Indices of sorted elements: [3 1 0 4 5 2]


### 12. 배열의 유니크 값 찾기
12-1. 배열 `arr = [1, 2, 2, 3, 4, 4, 4, 5]`에서 유니크 값을 찾으세요.

In [44]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
print(arr)

[1 2 2 3 4 4 4 5]


In [45]:
# 유니크 값
unique_values = np.unique(arr)
print("Unique values:", unique_values)

Unique values: [1 2 3 4 5]


### 13. 행렬 곱셈
13-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6], [7, 8]]`의 행렬 곱을 계산하세요.


In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [47]:
# 행렬 곱셈
matrix_product = np.dot(a, b)
print("Matrix product:\n", matrix_product)

Matrix product:
 [[19 22]
 [43 50]]


### 14. 조건부 선택
14-1. 배열 `arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`에서 짝수를 선택하세요.

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
# 조건부 선택
condition = arr % 2 == 0
even_numbers = arr[condition]
print("Even numbers:", even_numbers)

Even numbers: [ 2  4  6  8 10]


### 15. 브로드캐스팅
15-1. 배열 `a = [[1, 2, 3], [4, 5, 6]]`과 배열 `b = [1, 0, 1]`을 더하세요.

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 0, 1])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[1 0 1]


In [51]:
# 브로드캐스팅 연산
result = a + b
print("Broadcasting result:\n", result)

Broadcasting result:
 [[2 2 4]
 [5 5 7]]
