# Numpy 실습 (7/17)

### 1. NumPy 배열 생성 및 기본 연산

1-1. 배열 `a = [1, 2, 3]`과 `b = [4, 5, 6`을 생성하고 이 배열을 더하세요.

1-2. 배열 `a`와 `b`를 곱하세요.

### 2. 배열 생성 함수 사용

2-1. 2x3 형태의 0으로 초기화된 배열을 생성하세요.

2-2. 2x3 형태의 1로 초기화된 배열을 생성하세요.

2-3. 2x3 형태의 랜덤 값으로 채워진 배열을 생성하세요.


### 3. 배열 인덱싱 및 슬라이싱
3-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 인덱스 1의 요소를 출력하세요.

3-2. 배열 `arr`에서 인덱스 1부터 3까지의 요소를 출력하세요.

### 4. 배열 모양 변경
4-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`의 모양을 3x2로 변경하세요.

### 5. 배열 결합
5-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6]]`을 수직으로 결합하세요.

5-2. 배열 `a`와 `b`를 수평으로 결합하세요.

### 6. 배열 분할
6-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`을 수평으로 3등분하세요.

6-2. 배열 `arr`을 수직으로 2등분하세요.


### 7. 배열의 수학적 연산
7-1. 배열 `arr = [1, 2, 3, 4, 5]`의 합계를 구하세요.

7-2. 배열 `arr`의 평균을 구하세요.

7-3. 배열 `arr`의 표준 편차를 구하세요.

### 8. 논리 연산
8-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 20보다 큰 요소를 출력하세요.


### 9. 난수 생성 및 시드 설정
9-1. 3x3 형태의 난수 배열을 생성하세요.

9-2. 시드를 42로 설정한 후, 3x3 형태의 난수 배열을 생성하세요.

### 10. 배열 복사
10-1. 배열 `arr = [1, 2, 3, 4, 5]`의 뷰를 생성하고 첫 번째 요소를 10으로 변경하세요. 원본 배열을 확인하세요.

10-2. 배열 `arr`의 깊은 복사를 생성하고 첫 번째 요소를 20으로 변경하세요. 원본 배열을 확인하세요.

### 11. 배열 정렬
11-1. 배열 `arr = [5, 2, 9, 1, 5, 6]`을 정렬하세요.

11-2.정렬된 배열의 인덱스를 반환하세요.


### 12. 배열의 유니크 값 찾기
12-1. 배열 `arr = [1, 2, 2, 3, 4, 4, 4, 5]`에서 유니크 값을 찾으세요.

### 13. 행렬 곱셈
13-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6], [7, 8]]`의 행렬 곱을 계산하세요.


### 14. 조건부 선택
14-1. 배열 `arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`에서 짝수를 선택하세요.



### 15. 브로드캐스팅
15-1. 배열 `a = [[1, 2, 3], [4, 5, 6]]`과 배열 `b = [1, 0, 1]`을 더하세요.

In [ ]:
# 패키지 불러오기
import numpy as np

### 1. NumPy 배열 생성 및 기본 연산

1-1. 배열 `a = [1, 2, 3]`과 `b = [4, 5, 6`을 생성하고 이 배열을 더하세요.

1-2. 배열 `a`와 `b`를 곱하세요.

[1 2 3]
[4 5 6]


### 2. 배열 생성 함수 사용

2-1. 2x3 형태의 0으로 초기화된 배열을 생성하세요.

2-2. 2x3 형태의 1로 초기화된 배열을 생성하세요.

2-3. 2x3 형태의 랜덤 값으로 채워진 배열을 생성하세요.

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


### 3. 배열 인덱싱 및 슬라이싱
3-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 인덱스 1의 요소를 출력하세요.

3-2. 배열 `arr`에서 인덱스 1부터 3까지의 요소를 출력하세요.

[10 20 30 40 50]



### 4. 배열 모양 변경
4-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`의 모양을 3x2로 변경하세요.

[[1 2 3]
 [4 5 6]]


### 5. 배열 결합
5-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6]]`을 수직으로 결합하세요.

5-2. 배열 `a`와 `b`를 수평으로 결합하세요.

Horizontal stack:
 [[1 2 5]
 [3 4 6]]


### 6. 배열 분할
6-1. 배열 `arr = [[1, 2, 3], [4, 5, 6]]`을 수평으로 3등분하세요.

6-2. 배열 `arr`을 수직으로 2등분하세요.

Vertical split: [array([[1, 2, 3]]), array([[4, 5, 6]])]


### 7. 배열의 수학적 연산
7-1. 배열 `arr = [1, 2, 3, 4, 5]`의 합계를 구하세요.

7-2. 배열 `arr`의 평균을 구하세요.

7-3. 배열 `arr`의 표준 편차를 구하세요.

Standard Deviation: 1.4142135623730951


### 8. 논리 연산
8-1. 배열 `arr = [10, 20, 30, 40, 50]`에서 20보다 큰 요소를 출력하세요.

Elements greater than 20: [30 40 50]


### 9. 난수 생성 및 시드 설정
9-1. 3x3 형태의 난수 배열을 생성하세요.

9-2. 시드를 42로 설정한 후, 3x3 형태의 난수 배열을 생성하세요.

Seeded random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


### 10. 배열 복사
10-1. 배열 `arr = [1, 2, 3, 4, 5]`의 뷰를 생성하고 첫 번째 요소를 10으로 변경하세요. 원본 배열을 확인하세요.

10-2. 배열 `arr`의 깊은 복사를 생성하고 첫 번째 요소를 20으로 변경하세요. 원본 배열을 확인하세요.


Original array after copy modification: [10  2  3  4  5]


### 11. 배열 정렬
11-1. 배열 `arr = [5, 2, 9, 1, 5, 6]`을 정렬하세요.

11-2.정렬된 배열의 인덱스를 반환하세요.


Indices of sorted elements: [3 1 0 4 5 2]


### 12. 배열의 유니크 값 찾기
12-1. 배열 `arr = [1, 2, 2, 3, 4, 4, 4, 5]`에서 유니크 값을 찾으세요.

Unique values: [1 2 3 4 5]


### 13. 행렬 곱셈
13-1. 배열 `a = [[1, 2], [3, 4]]`와 `b = [[5, 6], [7, 8]]`의 행렬 곱을 계산하세요.


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### 14. 조건부 선택
14-1. 배열 `arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`에서 짝수를 선택하세요.

[ 1  2  3  4  5  6  7  8  9 10]


### 15. 브로드캐스팅
15-1. 배열 `a = [[1, 2, 3], [4, 5, 6]]`과 배열 `b = [1, 0, 1]`을 더하세요.